const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname,'..');
const noop=()=>{};
const ctx=new Proxy({createRadialGradient:()=>({addColorStop:noop})},{get:(t,k)=>t[k]||noop,set:(t,k,v)=>(t[k]=v,true)});
const canvas=()=>({getContext:()=>ctx,getBoundingClientRect:()=>({width:1080,height:820})});
const sandbox={window:{devicePixelRatio:3},document:{hidden:false,addEventListener:noop,removeEventListener:noop,createElement:canvas},ResizeObserver:class {observe(){} disconnect(){}},requestAnimationFrame:()=>1,cancelAnimationFrame:noop,performance:{now:()=>0},Math};
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(path.join(root,'dist/config.js'),'utf8'),sandbox);
vm.runInContext(fs.readFileSync(path.join(root,'dist/engine.js'),'utf8'),sandbox);
const Engine=sandbox.window.FireworksEngine;
const {shapes,profiles,detectDevice}=sandbox.window.FireworksConfig;
const defaults={shape:'chrysanthemum',shapeMode:'mixed',shapes,mode:'mixed',colors:['#ffc078','#ff796f','#ee9fcf','#ab97ff','#80caff','#8fe0c0'],color:'#ffc078',randomSize:true,size:85,sizeMin:55,sizeMax:130,density:180,quantity:8,interval:1.5,gravity:100,wind:0,trail:75,bloom:85,auto:false};
const engineFor=(s,profile='desktop')=>new Engine(canvas(),canvas(),()=>s,noop,noop,profile);
const mixed=engineFor(defaults);
mixed.launch(defaults);
assert.equal(new Set(mixed.queue.map(q=>q.settings.shape)).size,8,'Eight-shell batch must contain eight different selected shapes');
assert.equal(new Set(mixed.queue.map(q=>q.settings.size)).size,8,'Sizes must vary within a batch');
assert.ok(mixed.queue.every(q=>q.settings.size>=55&&q.settings.size<=130&&q.settings.palette.length===2));
mixed.launch({...defaults,quantity:6});
assert.equal(new Set(mixed.queue.map(q=>q.settings.shape)).size,14,'Shuffle bag must visit all fourteen shapes before repeating');
const selected={...defaults,shapes:['heart','crossette'],colors:['#ff796f','#80caff'],sizeMin:75,sizeMax:75};
mixed.clear();mixed.launch(selected);
assert.ok(mixed.queue.every(q=>selected.shapes.includes(q.settings.shape)&&q.settings.size===75&&q.settings.palette.every(c=>selected.colors.includes(c))));
const fixed={...defaults,shapeMode:'fixed',shape:'ring',mode:'single',color:'#112233',randomSize:false,size:95};
mixed.clear();mixed.launch(fixed);
assert.ok(mixed.queue.every(q=>q.settings.shape==='ring'&&q.color==='#112233'&&q.settings.size===95&&q.settings.palette.length===1));
let secondaryObserved=false,splitObserved=false,bouquetObserved=false;
for (const shape of shapes) {
  const s={...fixed,shape,quantity:1,mode:'mixed',size:150,gravity:200,wind:-100};
  const engine=engineFor(s);engine.launch(s);
  for (let frame=0;frame<660;frame++) {
    engine.tick(frame*1000/60);
    if (shape==='double'&&engine.secondary.length) secondaryObserved=true;
    if (shape==='crossette'&&engine.flares.length>1) splitObserved=true;
    if (shape==='bouquet'&&engine.secondary.length===5) bouquetObserved=true;
    assert.ok(engine.particles.every(p=>Number.isFinite(p.x+p.y+p.vx+p.vy)),'All trajectories must remain finite');
  }
  assert.equal(engine.particles.length+engine.rockets.length+engine.queue.length+engine.secondary.length+engine.flares.length,0,shape+' must fully expire');
  engine.destroy();
}
assert.ok(secondaryObserved,'Double shells must trigger their delayed inner burst');
assert.ok(splitObserved,'Crossette stars must split into daughter stars');
assert.ok(bouquetObserved,'Bouquet shells must schedule five delayed flower clusters');
assert.equal(detectDevice({userAgent:'Mozilla Android',maxTouchPoints:5},{width:412,height:915},true),'mobile');
assert.equal(detectDevice({userAgent:'Mozilla iPhone',maxTouchPoints:5},{width:390,height:844},true),'mobile');
assert.equal(detectDevice({userAgent:'Mozilla Macintosh',maxTouchPoints:5},{width:1366,height:1024},false),'mobile','iPad desktop UA must use mobile defaults');
assert.equal(detectDevice({userAgent:'Mozilla Windows',maxTouchPoints:10},{width:1920,height:1080},false),'desktop','Touchscreen PCs must keep desktop defaults');
assert.equal(detectDevice({userAgent:'Mozilla Windows',maxTouchPoints:0},{width:390,height:844},false),'desktop','A narrow desktop window is not a phone');
assert.ok(profiles.mobile.density*profiles.mobile.quantity/profiles.mobile.interval<profiles.desktop.density*profiles.desktop.quantity/profiles.desktop.interval/3);
const mobile=engineFor({...defaults,auto:false},'mobile');
assert.equal(mobile.dpr,1.5);
for(let i=0;i<3;i++)mobile.adaptQuality(20,25);
assert.equal(mobile.quality,0,'A brief slow frame must not change resolution');
mobile.adaptQuality(20,25);
assert.equal(mobile.quality,1);
assert.equal(mobile.dpr,1.25);
for(let i=0;i<4;i++)mobile.adaptQuality(20,25);
assert.equal(mobile.quality,2);assert.equal(mobile.maxParticles,1000);
for(let i=0;i<16;i++)mobile.adaptQuality(60,4);
assert.equal(mobile.quality,1,'Sustained headroom must restore quality gradually');
mobile.visibilityHandler();
assert.equal(mobile.statsClock+mobile.frames+mobile.frameWork+mobile.slowWindows+mobile.fastWindows,0);
mobile.setProfile('desktop');assert.equal(mobile.dpr,2);assert.equal(mobile.maxParticles,6500);
mobile.setProfile('mobile');
const mobileStress={...defaults,auto:false,quantity:10,density:300,shape:'crossette',shapeMode:'fixed'};
for(let frame=0;frame<360;frame++) {
  if(frame%3===0)mobile.launch(mobileStress);
  mobile.tick(frame*1000/60);
  assert.ok(mobile.particles.length<=1800);
  assert.ok(mobile.queue.length+mobile.rockets.length<=16);
}
mobile.clear();
assert.equal(mobile.activeGroups.length+mobile.renderGroups.size,0);
assert.ok(mobile.trailPool.length<=6500);
const recycled=mobile.trailPool[mobile.trailPool.length-1];
const sample={x:20,y:30};mobile.sampleTrail(sample);
assert.equal(sample.trail,recycled,'Expired particle trails must be reused');
assert.equal(sample.trailCount,1,'Reused histories must not connect unrelated fireworks');
const trail=sample.trail;mobile.elapsed+=0.04;sample.x=25;mobile.sampleTrail(sample);
assert.equal(sample.trail,trail,'Sampling must not allocate per-frame history objects');
const beforePause=mobile.elapsed;
mobile.inView=false;mobile.tick(100000);
assert.equal(mobile.elapsed,beforePause,'An offscreen sky must not keep simulating');
mobile.inView=true;mobile.visibilityHandler();mobile.tick(200000);
assert.ok(mobile.elapsed-beforePause<0.02,'Returning to the sky must not catch up the hidden time');
sandbox.document.hidden=true;
const hiddenTime=mobile.elapsed;mobile.tick(300000);
assert.equal(mobile.elapsed,hiddenTime);
sandbox.document.hidden=false;
const stress={...defaults,auto:true,quantity:10,density:300,interval:0.4,trail:100,bloom:100};
const engine=engineFor(stress);let peak=0;
for(let frame=0;frame<360;frame++) {
  if(frame%3===0)engine.launch(stress);
  engine.tick(frame*1000/60);
  peak=Math.max(peak,engine.particles.length);
  assert.ok(engine.particles.length<=6500);
  assert.ok(engine.queue.length+engine.rockets.length<=40);
  assert.ok(engine.secondary.length<=60&&engine.flares.length<=32);
  assert.ok(engine.queue.every((q,i,a)=>i===0||a[i-1].at<=q.at));
}
engine.clear();
assert.equal(engine.particles.length+engine.queue.length+engine.rockets.length+engine.secondary.length+engine.flares.length,0);
const html=fs.readFileSync(path.join(root,'dist/index.html'),'utf8');
for(const [,asset] of html.matchAll(/(?:src|href)="([^"#]+\.(?:js|css))(?:\?[^"#]*)?"/g))assert.ok(fs.existsSync(path.join(root,'dist',asset)));
assert.deepEqual([...html.matchAll(/data-shape="([^"]+)"/g)].map(match=>match[1]),Array.from(shapes));
console.log(JSON.stringify({mixedPoolAndRange:true,fixedMode:true,shapeCases:shapes.length,secondaryBurst:true,crossetteSplit:true,bouquetBurst:true,allParticlesExpire:true,deviceDetection:true,adaptiveQuality:true,trailReuse:true,offscreenPause:true,mobileCaps:true,stressPeak:peak,allCapsRespected:true,clear:true,assets:true}));
